name: Sanitizer GCC 12

on:
  push:
    branches: ["main"]

jobs:
  sanitizer_ubuntu_gcc12:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Generate Unix Makfiles
        run: cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc-12 -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-12 -Btarget -G "Unix Makefiles" -DSANITIZER:BOOL=ON
      - name: Build
        run: cmake --build target --config Debug
      - name: Test
        run: ctest --test-dir target -j10 -C Debug -T test --output-on-failure --verbose