name: Ubuntu WebAssembly build & test

on:
  push:
    branches: ["main"]

jobs:
  build-and-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update Node.js
        run: |
          nvm install latest
          nvm use latest
      - name: Install Emscripten SDK
        uses: mymindstorm/setup-emsdk@v14
      - name: Generate
        run: emcmake cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -Btarget
      - name: Build
        run: cmake --build target -- -j 16
      - name: Test
        run: ctest --test-dir target -C Release -T test --output-on-failure -VV
      - name: Release
        run: |
          xcopy target\test\test_core.js release\ /s /y
          xcopy target\test\test_core.wasm release\ /s /y
          xcopy target\test\test_core_report.xml release\ /s /y
          xcopy target\src\libcore.a release\ /s /y
          xcopy interface\core release\core\ /s /y
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu_webassembly
          path: release\**
