name: Ubuntu WebAssembly build & test

on:
  push:
    branches: ["main"]

jobs:
  build-and-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          git pull
          emsdk install latest
          emsdk activate latest
      - name: Generate
        run: |
          source ./emsdk_env.sh
          emcmake cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -Btarget
      - name: Build
        run: cmake --build target -- -j 16
      - name: Test
        run: ctest --test-dir target -C Release -T test --output-on-failure -VV
      - name: Release
        run: |
          mkdir -p release
          cp -R target/test/test_core.js release -i
          cp -R target/test/test_core.wasm release -i
          cp -R target/test/test_core_report.xml release -i
          cp -R target/src/libcore.a release -i
          cp -R interface/core release/core -i
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu_webassembly
          path: release/**
