name: Windows clang-cl 2022 x86-64 build & test

on:
  push:
    branches: ["main"]

jobs:
  build-and-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Generate visual Studio solution
        run: cmake.exe --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE "-DCMAKE_C_COMPILER:FILEPATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\Llvm\x64\bin\clang-cl.exe" "-DCMAKE_CXX_COMPILER:FILEPATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\Llvm\x64\bin\clang-cl.exe" -Btarget -G "Visual Studio 17 2022" -T ClangCL,host=x64 -A x64
      - name: Build
        run: cmake.exe --build target --config Release --parallel
      - name: Test
        run: ctest --test-dir target -C Release -T test --output-on-failure -VV
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Core Test Report (Windows clang-cl 2022 x86-64)
          path: target/test/test_core_report.xml
          reporter: java-junit
      - name: Release
        run: |
          xcopy target\test\Release release\ /s /y
          xcopy target\test\test_core_report.xml release\ /s /y
          xcopy target\src\Release release\ /s /y 
          xcopy interface\core release\core\ /s /y
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows_clang_cl_2022_x64
          path: release\**
