name: Windows

on: [push]

jobs:
  build-and-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Generate visual Studio solution
        run: cmake.exe --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Btarget -G "Visual Studio 17 2022" -T host=x64 -A x64
      - name: Build
        run: cmake.exe --build target --config Release
      - name: Test
        run: |
          cd target
          ctest -j10 -C Release -T test --output-on-failure
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Core Test Report
          path: target/test/test_core_report.xml
          reporter: java-junit
      - name: Release
        run: | 
          xcopy target\test\Release release\ /s /y
          xcopy target\src\Release release\ /s /y
          xcopy src\core release\core\ /s /y
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Windows_MSVC_AMD64
          path: release\**

  test-coverage:
    runs-on: windows-latest
    needs: build-and-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Generate visual Studio solution
        run: cmake.exe --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Btarget -G "Visual Studio 17 2022" -T host=x64 -A x64
      - name: Build
        run: cmake.exe --build target --config Debug
      - name: Test covering
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\CodeCoverage.Console\Microsoft.CodeCoverage.Console.exe" instrument test_core.exe
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\CodeCoverage.Console\Microsoft.CodeCoverage.Console.exe" collect test_core.exe -o core -f xml
      - name: Upload to Codecov
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe
          .\codecov.exe -f target\test\Debug\core.xml
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Windows_MSVC_AMD64
          path: target\test\Debug\core.xml